### ISSUE TITLE
Not work anymore

### ISSUE THREAD

**Issue by carlosgonz0** [webmeister/plugin.video.youtube.channels#10]

**Comment by toff** [comment]
Looks like a bug with the youtube-dl addon :
https://github.com/ruuk/script.module.youtube.dl/issues/55

I applied the modification and this addon works again.

**Comment by carlosgonz0** [comment]
Thank you @toff @webmeister

**Comment by carlosgonz0** [comment]
Hi @toff, how to fix this issues? i still can not play video.
